In [13]:
#import dependencies
import pandas as pd
import numpy as np
from datetime import datetime

In [14]:
#Import data from citi bike data
feb_2021 = "raw_data/JC-202102-citibike-tripdata.csv"
mar_2021 = "raw_data/JC-202103-citibike-tripdata.csv"
apr_2021 = "raw_data/JC-202104-citibike-tripdata.csv"
may_2021 = "raw_data/JC-202105-citibike-tripdata.csv"
jun_2021 = "raw_data/JC-202106-citibike-tripdata.csv"
jul_2021 = "raw_data/JC-202107-citibike-tripdata.csv"
aug_2021 = "raw_data/JC-202108-citibike-tripdata.csv"
sept_2021 ="raw_data/JC-202109-citibike-tripdata.csv"
oct_2021 = "raw_data/JC-202110-citibike-tripdata.csv"
nov_2021 = "raw_data/JC-202111-citibike-tripdata.csv"
dec_2021 = "raw_data/JC-202112-citibike-tripdata.csv"
jan_2022 = "raw_data/JC-202201-citibike-tripdata.csv"
feb_2022 = "raw_data/JC-202202-citibike-tripdata.csv"
mar_2022 = "raw_data/JC-202203-citibike-tripdata.csv"
apr_2022 = "raw_data/JC-202204-citibike-tripdata.csv"
may_2022 = "raw_data/JC-202205-citibike-tripdata.csv"
jun_2022 = "raw_data/JC-202206-citibike-tripdata.csv"

df_feb_2021 = pd.read_csv(feb_2021, encoding="ISO-8859-1")
df_mar_2021 = pd.read_csv(mar_2021, encoding="ISO-8859-1")
df_apr_2021 = pd.read_csv(apr_2021, encoding="ISO-8859-1")
df_may_2021 = pd.read_csv(may_2021, encoding="ISO-8859-1")
df_jun_2021 = pd.read_csv(jun_2021, encoding="ISO-8859-1")
df_jul_2021 = pd.read_csv(jul_2021, encoding="ISO-8859-1")
df_aug_2021 = pd.read_csv(aug_2021, encoding="ISO-8859-1")
df_sept_2021 = pd.read_csv(sept_2021, encoding="ISO-8859-1")
df_oct_2021 = pd.read_csv(oct_2021, encoding="ISO-8859-1")
df_nov_2021 = pd.read_csv(nov_2021, encoding="ISO-8859-1")
df_dec_2021 = pd.read_csv(dec_2021, encoding="ISO-8859-1")
df_jan_2022 = pd.read_csv(jan_2022, encoding="ISO-8859-1")
df_feb_2022 = pd.read_csv(feb_2022, encoding="ISO-8859-1")
df_mar_2022 = pd.read_csv(mar_2022, encoding="ISO-8859-1")
df_apr_2022 = pd.read_csv(apr_2022, encoding="ISO-8859-1")
df_may_2022 = pd.read_csv(may_2022, encoding="ISO-8859-1")
df_jun_2022 = pd.read_csv(jun_2022, encoding="ISO-8859-1")

In [15]:
# Combining all csv files, since no unique join column id
df = df_feb_2021.append(df_feb_2021, sort=False)
df = df.append(df_mar_2021, sort=False)
df = df.append(df_apr_2021, sort=False)
df = df.append(df_may_2021, sort=False)
df = df.append(df_jun_2021, sort=False)
df = df.append(df_jul_2021, sort=False)
df = df.append(df_aug_2021, sort=False)
df = df.append(df_sept_2021, sort=False)
df = df.append(df_oct_2021, sort=False)
df = df.append(df_nov_2021, sort=False)
df = df.append(df_dec_2021, sort=False)
df = df.append(df_jan_2022, sort=False)
df = df.append(df_feb_2022, sort=False)
df = df.append(df_mar_2022, sort=False)
df = df.append(df_apr_2022, sort=False)
df = df.append(df_may_2022, sort=False)
df = df.append(df_jun_2022, sort=False)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103294,25AD34565A260732,classic_bike,2022-06-17 16:03:36,2022-06-17 16:33:48,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,casual
103295,8A4181FCE9439036,classic_bike,2022-06-25 14:14:26,2022-06-25 14:19:40,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,8 St & Washington St,HB603,40.736982,-74.027781,40.745984,-74.028199,member
103296,28C8501BCB596743,electric_bike,2022-06-04 08:57:04,2022-06-04 09:15:33,Jersey & 6th St,JC027,11 St & Washington St,HB502,40.725289,-74.045572,40.749985,-74.027150,casual
103297,D28575BBFF3A0B57,classic_bike,2022-06-17 06:11:05,2022-06-17 06:21:37,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member
103298,A914FEF9390C201C,electric_bike,2022-06-02 18:15:17,2022-06-02 18:20:22,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member

In [16]:
df['ended_at'] = pd.to_datetime(df.ended_at)

In [17]:
df['started_at'] = pd.to_datetime(df.started_at)

In [18]:
df['trip_duration_min'] = (df['ended_at'] - df['started_at']).dt.total_seconds() / 60

In [19]:
df.count()

ride_id               994353
rideable_type         994353
started_at            994353
ended_at              994353
start_station_name    994353
start_station_id      994353
end_station_name      989554
end_station_id        989554
start_lat             994353
start_lng             994353
end_lat               991130
end_lng               991130
member_casual         994353
trip_duration_min     994353
dtype: int64

In [20]:
df = df.dropna(how='any')
df.count()

ride_id               989554
rideable_type         989554
started_at            989554
ended_at              989554
start_station_name    989554
start_station_id      989554
end_station_name      989554
end_station_id        989554
start_lat             989554
start_lng             989554
end_lat               989554
end_lng               989554
member_casual         989554
trip_duration_min     989554
dtype: int64

In [21]:
#df.to_csv('citibike.csv', index=False)